language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4snapshot'

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --no-interaction

script:
  - composer all-ci

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
